title: Default Page
preset: page
fields:
  date:
    label: Publication date
    type: date
    width: 1/3
  keywords:
    label: Keywords
    type: tags
    width: 2/3
    options: query
    query: page.index.pluck("keywords", ",", true)
  authors:
    label: Authors
    type: tags
    options: query
    query: page.index.pluck("authors", ",", true)
  categories:
    label: Categories
    type: checkboxes
    options:
      philosophy: Philosophy
  language:
    label: Language
    type: radio
    default: francais
    options:
      francais: Français
      english: English
  text:
    label: Text
    type: textarea
    size: large


